language: node_js
cache:
    npm: false
node_js:
- lts/*
before_script:
- npm install -g grunt-cli npm
env:
  global:
    secure: ABatXXM9lXYQ80Ro0nJ15j5BG/XEP5/L3kGEk+HrOOWrfZHvT3Xd1mQFkHBR5UinNy2Kv/IcUu/2eO1t8ZrX0KlZbx32Y/MuinZKsAWDs8Rx3CsqMIU5f9bk6lhvGLcCFL1AN4gn+0Ga1Ta7ggW9MhhscF2cf1j24tZAxK4D48HQZYK3JQ13nhhsM3RIr9nhpipQMBoTyqTFFgRtjGQJHq7kpAV/7yGpP1K5xgarUnzT1hg9n4w3WVlSZRHPLyyBf7+6anWyANBGkqj9w9ggI93aCe/MTP6kHEftMBVrjFrQZgZZW0D5SdxKbY6n4llLK4adnsyXEXQE9Q+iwsaFLYB0hlQgX3BxReaoCc0MwG95lSZ/U7jFZ6KJL/NIoju0zyNiTlnWBz5arvoxEL1yZ+Nq1KKVHykgwVzhrjoyOSHFt7FtMrvm3WCe0NR7sUcDbo2L3ccbWvIMYkvs8A1SrIOUICapet+t+iF5r53VqRwQF6oA7kOM+gZ+sdHOnmsnCwzWWSCkamMZUx2CCzKFERGUP20Yz3UuUGPMYsthSfVpq5Ds0t90voW2RUQa2cgS3nRLaUA+FjWF4wFSkfqS9NxSkK0etiZRYqGNtB/WnQFEKySWsyC9m1rHDn2LlKDrxTgz5d8b7pSXaWU68JMxJEBz4h9HXR/GEdSEqaeIgYQ=
